__author__ = 'giulio'

import re
import os
import csv
import sys

def addPublications(templateSection, templateNewPaper, pubslistPath):
    # Template for paper section
    with open(templateSection, 'r') as f:
        templateSectionRaw = f.read()
        f.close()
    with open(templateNewPaper, 'r') as f:
        templateNewPaperRaw = f.read()
        f.close()
        
    with open(pubslistPath, 'rb') as csvFile:
        rows = csv.reader(csvFile, delimiter = ',')
        newSection = False
        sectionTitle = ''
        publications = []
        section = []
        
        for row in rows:
            if len(row) == 0:
                if not len(sectionTitle) == 0 and not len(publications) == 0:
                    section.append((templateSectionRaw % ('\n'.join(publications))).replace('currSection', sectionTitle))
                    sectionTitle = ''
                    publications = []
                newSection = True
                continue
            if newSection:
                sectionTitle = row[0]
                newSection = False
                rows.next()
                continue
            
            if not len(row) == 8:
                print 'Check entry:\n%s\n8 required arguments' % row
                sys.exit()
                
            newPaper = (templateNewPaperRaw % tuple(row[0:-3])).replace('currSection', sectionTitle.replace(' ', '')).replace('fileName', row[-3])
            
            # Remove parts not valid
            if int(row[-1]) == 0:
                parts = newPaper.split('<!-- Poster -->')
                newPaper = parts[0] + parts[2]
            if int(row[-2]) == 0:
                parts = newPaper.split('<!-- Word cloud -->')
                newPaper = parts[0] + '\n<div>\n' + parts[2]
            if len(row[-3]) == 0:
                parts = newPaper.split('<!-- Links -->')
                newPaper = parts[0] + parts[2]
            
            publications.append(newPaper)
        
        if not len(sectionTitle) == 0 and not len(publications) == 0:
            section.append((templateSectionRaw % ('\n'.join(publications))).replace('currSection', sectionTitle))
                
    return '\n'.join(section)
    

# testing main
if __name__ == '__main__':
    
    # filenames
    pubsList = '/Users/giulio/Dropbox (Personal)/Giulio/Education/4_PhD/Publications/publications.csv'
    templatePubsSection = '/Users/giulio/Dropbox (Personal)/Giulio/Sites/current/autogeneration/publicationsSection.html'
    templateNewPaper = '/Users/giulio/Dropbox (Personal)/Giulio/Sites/current/autogeneration/newPaper.html'
    templatePublications = '/Users/giulio/Dropbox (Personal)/Giulio/Sites/current/autogeneration/publications.html'
    outPublications = '/Users/giulio/Dropbox (Personal)/Giulio/Sites/current/publications.html'
    
    
    publications = addPublications(templatePubsSection, templateNewPaper, pubsList)
    with open(templatePublications, 'rb') as f:
        publicationsToFill = f.read()
        f.close()
    publicationsToFill = publicationsToFill.split('<!-- Automatic generated: block 1 -->')
    publicationsFilled = publicationsToFill[0] + '<!-- Autogenerated: start-->\n' + publications + '<!-- Autogenerated: end -->\n' +  publicationsToFill[1]
    
    # write file
    with open(outPublications, 'w') as f:
        f.write(publicationsFilled)
        f.close()

    print('File generated: %s' % outPublications)
