#!/bin/bash
# To setup auto refreshing on mac
# cp com.giuliomarin.website.plist $HOME/Library/LaunchAgents/
# launchctl load $HOME/Library/LaunchAgents/com.giuliomarin.website.plist
## (to stop) launchctl unload $HOME/Library/LaunchAgents/com.giuliomarin.website.plist

# check connectivity
ping -c1 www.google.com > /dev/null
if [ "$?" != 0 ]; then
  echo "No internet connection"
  exit 0
else
  echo "Connected to internet"
fi

# go to main folder
pushd `dirname $0`/.. > /dev/null

# reset branch
git reset
rm data.html log.txt log_parse.txt
touch tmpfile # to avoid then stash pop an old stash
git stash
git pull
git stash pop
rm tmpfile

# download web pages
if [[ "`uname`" == 'Darwin' ]]; then
  COMMAND="curl"
else
  COMMAND="wget -O -"
fi

# download pages
mkdir -p downloaded
$COMMAND "https://scholar.google.com/citations?user=t9UpeEAAAAAJ&hl=en" > downloaded/googlescholar_giuliomarin.html
# $COMMAND "https://www.runtastic.com/en/users/07b82bdf-b0df-9b46-97f1-0e6d19b40d88/statistics" > downloaded/runtastic_giuliomarin.html
echo "Updated on `date`" > log.txt

# pasre pages
python scripts/parsehtml.py > log_parse.txt 2>&1

# commit and push if different
if git status | grep "data.html"; then
  git add data.html log.txt log_parse.txt
  git commit -m "[**generated**] Update data from `hostname`"
  git push
fi

popd > /dev/null
